"""
Django settings for backshop project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vbnwcj8tgk%h1mh4^ss46x&c4g*!h*n6jmticc4z7%m+pvsc^g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'shop_db',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

#Сховище зображень

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# django-unfold (UI адмін-панелі django)

UNFOLD = {
    # 🏷 Заголовки
    "SITE_TITLE": "Сервісний центр",
    "SITE_HEADER": "Панель адміністратора",
    "SITE_SUBHEADER": "Керування системою",

    # 🧭 Брендинг
    "SITE_SYMBOL": "🛠",
    "SITE_LOGO": None,  # або шлях до твого логотипу
    "SITE_ICON": None,

    # 🎨 Кольори (сучасний синьо-фіолетовий стиль)
    "COLORS": {
        "primary": {
            "50": "oklch(97% 0.02 270)",
            "100": "oklch(94% 0.04 270)",
            "200": "oklch(88% 0.08 270)",
            "300": "oklch(80% 0.12 270)",
            "400": "oklch(70% 0.18 270)",
            "500": "oklch(62% 0.22 270)",
            "600": "oklch(55% 0.24 270)",
            "700": "oklch(45% 0.22 270)",
            "800": "oklch(35% 0.20 270)",
            "900": "oklch(25% 0.18 270)",
        }
    },

    # 🧭 Меню (sidebar)
    "SIDEBAR": {
        "show_search": True,
    },

    "SITE_DROPDOWN": [
        {
            "title": "Головна сторінка",
            "icon": "home",
            "link": "/",
        },
        {
            "title": "Документація API",
            "icon": "code",
            "link": "/api/",
        },
    ],

    # 👤 Доступ користувачів (опційно)
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
}